### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by xs005** [lsst-sqre/kafkit#10]
I like this async kafka package.

I guess I think something wrong at manager.py line 96. I changed it to `schema["name"] = f'{schema["name"]}{self._suffix}'`

I am a new developer, where can I create a ticket and corresponding branch if I want to help?

**Comment by jonathansick** [comment]
Hi @xs005 thanks for spotting this! Clearly I need to do more testing 😄 I went ahead and pushed a fix and released a new beta, `0.2.0b3` to PyPI so you can use this fixed version more easily.

Feel free to send PRs using GitHub's [usual system](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). As a contributor outside LSST/Rubin Observatory, you can name the branch as you please and submit a PR. We'll take care of reviewing and merging it. Don't worry about tickets in our Jira system.

[This page in our docs](https://kafkit.lsst.io/dev/development.html) explains the particular steps for developing Kafkit.

Again, thanks so much for your contribution!
