### ISSUE TITLE
Fetch Schemas from schema registry url

### ISSUE THREAD

**Issue by HuM4NoiD** [lsst-sqre/kafkit#17]
I have a schema registry url and I want to build kafka consumers, Currently I don't have access to the schema files.
What should I do to fetch all relevant schemas for the topics I want to listen to?
I can only spot a register method to register schemas to the registry and serialize method to serialize messages.
What should I do so that I can deserialize messages?

I am using kafkit version 0.2.1

**Comment by jonathansick** [comment]
Right, we only have [API documentation for `Deserializer`](https://kafkit.lsst.io/api/kafkit.registry.Deserializer.html#kafkit.registry.Deserializer) which describes the fact that it obtains schemas on-demand from the Confluent Schema Registry. We'll add a user guide at some point that'll make this clearer.

**Comment by HuM4NoiD** [comment]
On another note, is there a way to prefetch/cache schemas manually before hand by subject? so that some time is saved when deserializing? I am guessing that the first deserialization will fetch and cache the schema. I did spot a [method](https://kafkit.lsst.io/api/kafkit.registry.sansio.RegistryApi.html#kafkit.registry.sansio.RegistryApi.get_schema_by_subject) that can directly fetch a schema by subject. Does this cache the schema for subsequent deserializations?
